FROM php:7.4-fpm-alpine

ENV COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_DISABLE_XDEBUG_WARN=1 \
    PHPREDIS_VERSION=5.1.1

ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

RUN set -xe \
    && apk add --no-cache --virtual .build-deps \
        tzdata \
        $PHPIZE_DEPS \
    && apk add gnu-libiconv --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted \
    && cp /usr/share/zoneinfo/UTC /etc/localtime \
    && echo 'UTC' > /etc/localtime \
    && apk add --no-cache \
        openssl-dev \
        bash \
        # freetype-dev \
        # libpng-dev \
        # libjpeg-turbo-dev \
        sqlite-dev \
        curl \
    	curl-dev \
        libsodium-dev \
        icu-dev \
        libxml2-dev \
        recode-dev \
        libxslt-dev \
        git \
        postgresql-client \
        postgresql-dev \
        openssh-client \
        libmcrypt-dev \
        libmcrypt \
        libzip-dev \
        libgcrypt-dev \
        oniguruma-dev \
    && apk --update --no-cache add grep \
    && mkdir -p /usr/src/php/ext/redis \
    && curl -L https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz | tar xvz -C /usr/src/php/ext/redis --strip 1 \
    && echo 'redis' >> /usr/src/php-available-exts \
    # && docker-php-ext-configure gd \
    #    --with-freetype=/usr/include/ \
    && docker-php-ext-install -j$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) \
        # gd \
        bcmath \
        opcache \
        iconv \
        mysqli \
        pdo \
        pdo_mysql \
        pdo_sqlite \
        pdo_pgsql \
        zip \
        xml \
        xsl \
        intl \
        json \
        mbstring \
        curl \
        simplexml \
        soap \
        bcmath \
        redis \
        sockets \
        tokenizer \
        xml \
        zip \
        # todo add libs
    && docker-php-ext-install sodium \
    # && docker-php-ext-install -j$(nproc) gd \
    # && docker-php-ext-enable gd \
    && apk del .build-deps \
    && rm -rf /tmp/* /var/cache/apk/*

# Setup GD
RUN apk add --no-cache \
        freetype \
        libjpeg-turbo \
        libpng \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd \
        --with-freetype=/usr/include/ \
        # --with-png=/usr/include/ \ # No longer necessary as of 7.4; https://github.com/docker-library/php/pull/910#issuecomment-559383597
        --with-jpeg=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-enable gd \
    && apk del --no-cache \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
    && rm -rf /tmp/*

COPY fix-permission /bin/
RUN chmod +x /bin/fix-permission

WORKDIR /var/www/html
